### ISSUE TITLE
New metrics that are not in the README.md

### ISSUE THREAD

**Issue by hassiahk** [enochkan/torch-metrics#10]
Hello together,

I am thinking of adding following metrics to the library:
- `ExplainedVariance`
- `PSNR (Peak Signal-to-Noise Ratio)`
- `SSIM (Structual Similarity Index Measure)`
- `Fbeta`
- `Poisson`
- `MeanSquaredLogError`
- `MeanAbsolutePercentageError`
- `TruePositives`
- `FalsePositives`
- `TrueNegatives`
- `FalseNegatives`

Let me know which of these will not be useful or redundant metrics. Also @enochkan, is it okay to raise a new issue everytime if I want to include a new metric or just a PR would be sufficient?

**Comment by enochkan** [comment]
I think a pull request will suffice. Just make sure you update the docs in your pull request as well.
