### ISSUE TITLE
Code Linting

### ISSUE THREAD

**Issue by hassiahk** [enochkan/torch-metrics#18]
Hello Together.

Should we use code linting (`pylint` or `flake8`) for better standards of the code? We can also add this as a check in CI so that contributors will also follow some coding standards.

**Comment by enochkan** [comment]
Sorry work's been overwhelmingly busy. @hassiahk if you want I can add pre-commit hooks with flake8, sort and black formatting checks.

**Comment by hassiahk** [comment]
@enochkan, that would be great!!

**Comment by enochkan** [comment]
closing this issue as pre-commit hooks are added. can further refactor 👍
