### ISSUE TITLE
Tests for MSLE

### ISSUE THREAD

**Issue by hassiahk** [enochkan/torch-metrics#19]
Hello @Vijayabhaskar96, is there any reason why you did not test `MeanSquaredLogarithmicError` with normally distributed data?

https://github.com/enochkan/torch-metrics/blob/7ce99293f80f8b9144357d119a1332f199db140d/tests/test_regression_metrics.py#L54-L64

**Comment by Vijayabhaskar96** [comment]
Hi, Log of negative numbers is NaN. You can't have negative numbers for `MeanSquaredLogarithmicError` as far as I know. 
Sklearn [source](https://github.com/scikit-learn/scikit-learn/blob/0fb307bf39bbdacd6ed713c00724f8f871d60370/sklearn/metrics/_regression.py#L334)

**Comment by hassiahk** [comment]
Damn, how did I miss that 😅. Thanks @Vijayabhaskar96.
