### ISSUE TITLE
NLP Metrics

### ISSUE THREAD

**Issue by ghost** [enochkan/torch-metrics#29]
Hi,

We need metrics for natural language processing, including:
1. BLEU
2. CIDER
3. METEOR
4. ROUGE_L
5. SPICE

Some of these metrics have original implementations using Java. I'm wondering if there is any limitations regarding the dependencies that we could have in torch-metrics? 
If not I can adapt all metrics to torch-metrics as an initial step.

**Comment by enochkan** [comment]
@aligholami wonderful suggestions. We currently do not have any NLP metrics so it'll be great to implement those in PyTorch. Feel free to reorganize the structure of the repo in your fork and submit a PR. 👍
