### ISSUE TITLE
Vision Metrics

### ISSUE THREAD

**Issue by ghost** [enochkan/torch-metrics#30]
Hi,

We need metrics for some specific vision tasks such as Object Detection, Instance Segmentation, Keypoint Detection, etc.
These metrics include:
1. Mean Average Precision
2. Intersection Over Union
...

The original implementation is based on the pycocotools library, I can adapt them to torch-metrics if everyone agrees.

**Comment by enochkan** [comment]
@aligholami thanks for the suggestion. We do have MeanIoU implemented but it'll be great if you can implement a base IoU class and extend that to MeanIoU. It'll also be great to have mAP implemented in torch as well. Feel free to submit a PR.
