### ISSUE TITLE
Code formatting and docstrings for all functions

### ISSUE THREAD

**Issue by hassiahk** [enochkan/torch-metrics#4]
```
class MeanAbsoluteError:
    def __call__(self, tensor1, tensor2):
        """
        Arguments
        ---------
        x : torch.Tensor
        y : torch.Tensor
        """
        return torch.mean(torch.abs(tensor1 - tensor2))
```
Instead of `tensor1` and `tensor2` like above it would be great if we can change it to `y_true` and `y_pred` and also with concise docstrings like below.
```
class MeanAbsoluteError:
    def __call__(self, y_true, y_pred):
        """
        Computes the Mean Absolute error between the `y_true` and `y_pred`
        Args:
        y_true: Ground truth values.
        y_pred: The predicted values.
    Returns:
        Mean Absolute error
    """
        return torch.mean(torch.abs(y_true - y_pred))
```
I am very sorry if this sounds a bit rude. I am just thinking if we can make small things better it will attract more people.

**Comment by hassiahk** [comment]
@enochkan I can start working on this right away, if it is okay with you. Do let me know :)

**Comment by enochkan** [comment]
@hassiahk hey great suggestions and definitely! I am quite occupied at the moment but once you've made the changes I can review and merge your pull requests. Thanks for taking the time to work on this.

**Comment by hassiahk** [comment]
Okay, I will start tomorrow then. It's already midnight in India xD

**Comment by enochkan** [comment]
Haha no rush at all. Thanks for all your help!
