### ISSUE TITLE
Client specific errors

### ISSUE THREAD

**Issue by zutshianand** [enochkan/torch-metrics#7]
Hi all,

Client specific error handling in the methods are not present and ideally should be added. We should return proper exceptions to the client related to the incorrect and erroneous attributes in the method.

Thanks

**Comment by hassiahk** [comment]
Hi @zutshianand. That's a great idea. Can you also provide an example of how it should be? 

And we can also handle most of the exceptions (like converting `y_pred` and `y_true` to tensors, casting `y_pred` and `y_true` to have same `dtype` when necessary etc) in our methods without prompting the user to do it. @enochkan and @zutshianand, what do you guys think?

**Comment by enochkan** [comment]
yep we can try to convert to tensors and have a catch block in case the conversion fails. Does any one of you want to implement this?

**Comment by hassiahk** [comment]
I will take this up, but I am a bit packed this week. So, I probably will finish it by next week. Hope that is okay.

**Comment by enochkan** [comment]
sounds good. Thanks @hassiahk
