### ISSUE TITLE
Exhaustive list of metrics

### ISSUE THREAD

**Issue by zutshianand** [enochkan/torch-metrics#8]
Hi all,

Please find the below list of exhaustive metrics provided by sklearn to date. We can use that as reference while implementing them in Pytorch.

```
    'accuracy_score',
    'adjusted_mutual_info_score',
    'adjusted_rand_score',
    'auc',
    'average_precision_score',
    'balanced_accuracy_score',
    'calinski_harabaz_score',
    'calinski_harabasz_score',
    'check_scoring',
    'classification_report',
    'cluster',
    'cohen_kappa_score',
    'completeness_score',
    'ConfusionMatrixDisplay',
    'confusion_matrix',
    'consensus_score',
    'coverage_error',
    'dcg_score',
    'davies_bouldin_score',
    'euclidean_distances',
    'explained_variance_score',
    'f1_score',
    'fbeta_score',
    'fowlkes_mallows_score',
    'get_scorer',
    'hamming_loss',
    'hinge_loss',
    'homogeneity_completeness_v_measure',
    'homogeneity_score',
    'jaccard_score',
    'jaccard_similarity_score',
    'label_ranking_average_precision_score',
    'label_ranking_loss',
    'log_loss',
    'make_scorer',
    'nan_euclidean_distances',
    'matthews_corrcoef',
    'max_error',
    'mean_absolute_error',
    'mean_squared_error',
    'mean_squared_log_error',
    'mean_poisson_deviance',
    'mean_gamma_deviance',
    'mean_tweedie_deviance',
    'median_absolute_error',
    'multilabel_confusion_matrix',
    'mutual_info_score',
    'ndcg_score',
    'normalized_mutual_info_score',
    'pairwise_distances',
    'pairwise_distances_argmin',
    'pairwise_distances_argmin_min',
    'pairwise_distances_chunked',
    'pairwise_kernels',
    'plot_confusion_matrix',
    'plot_precision_recall_curve',
    'plot_roc_curve',
    'PrecisionRecallDisplay',
    'precision_recall_curve',
    'precision_recall_fscore_support',
    'precision_score',
    'r2_score',
    'recall_score',
    'RocCurveDisplay',
    'roc_auc_score',
    'roc_curve',
    'SCORERS',
    'silhouette_samples',
    'silhouette_score',
    'v_measure_score',
    'zero_one_loss',
    'brier_score_loss',
```

**Comment by hassiahk** [comment]
Hi @zutshianand, we are trying to implement metrics that are available in `tf.keras.metrics` module. So, I would say implementing those would suffice and I don't think all of the available metrics in `sklearn` are useful in Deep Learning. What do you say? @enochkan

**Comment by enochkan** [comment]
@hassiahk @zutshianand thanks for all the useful suggestions. I think we can keep a running list of metrics we want to implement, and I certainly think we can implement these metrics from `sklearn` at some point. I can modify the readme later.

**Comment by hassiahk** [comment]
Yes, I am not against implementing them, I am just curious whether we need all of those or not.

**Comment by enochkan** [comment]
@hassiahk @zutshianand what do you guys think is a good way to keep track of metrics that we plan to implement/ have already implemented? A google doc? Any ideas?

**Comment by zutshianand** [comment]
Yes @enochkan, I think a google sheet would be nice with respective owners and ETA assigned. What are your thoughts?

**Comment by enochkan** [comment]
yup let's do it.

**Comment by enochkan** [comment]
@zutshianand will you be able to start a google sheet for the metrics we plan to implement?

**Comment by zutshianand** [comment]
Sure @enochkan I will create one and share.

**Comment by hassiahk** [comment]
@zutshianand I have created one and shared in this issue https://github.com/enochkan/torch-metrics/issues/15
