### ISSUE TITLE
Regarding Object detection metrics

### ISSUE THREAD

**Issue by Vijayabhaskar96** [enochkan/torch-metrics#9]
Found this repo from Reddit, great project. I was actually struggling to find a proper resource that implements Object detection metrics like Mean Average Precision which has several versions itself, depending upon the evaluating competition, I found [this paper](https://github.com/rafaelpadilla/Object-Detection-Metrics/raw/master/paper_survey_on_performance_metrics_for_object_detection_algorithms.pdf) which explains everything in detail and provides a [library](https://github.com/rafaelpadilla/Object-Detection-Metrics) implementing everything, but that is in numpy and the code is pretty messy, I would like to contribute a Pytorch version of their implementation with clear API, but may take a while as I'm just learning this stuff and need time to make sure the implementation is correct.

**Comment by hassiahk** [comment]
Hi @Vijayabhaskar96, I have seen the paper and the repo that you mentioned and I agree with you, the code is really messy. From the repo, what I understand is that the metrics for Objection Detection are mainly different variants using Precision and Recall. We have already implemented Precision and Recall in this library, so feel free to built on top of them. Please correct me, if my understanding is wrong in any way.

**Comment by Vijayabhaskar96** [comment]
I would use the parent library metrics wherever possible, but in object detection case the precision and recall are calculated differently based bounding box IOU thresholds, therefore can't use precision and recall metrics designed for classification.

**Comment by hassiahk** [comment]
Thanks @Vijayabhaskar96 for clarifying it, I did not know that until now. :) Let me know if you need any help in any way.
